# Generated by Django 4.2.5 on 2023-10-04 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cart_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'Cart Item', 'verbose_name_plural': 'Cart Items'},
        ),
        migrations.RenameField(
            model_name='logstatus',
            old_name='cart_id',
            new_name='cart',
        ),
        migrations.RenameField(
            model_name='logstatus',
            old_name='status_id',
            new_name='status',
        ),
    ]
