# Generated by Django 4.2.5 on 2023-10-02 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_remove_cart_foods_cartitem_cart_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='price',
            field=models.IntegerField(default=1, verbose_name='price'),
            preserve_default=False,
        ),
    ]
