# Generated by Django 4.2.5 on 2023-10-02 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_alter_cartitem_cart_alter_cartitem_food_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='final_price',
        ),
    ]
