# Generated by Django 4.2.5 on 2023-10-02 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
        ('cart', '0005_remove_cart_final_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(through='cart.CartItem', to='food.food', verbose_name='items'),
        ),
    ]
