# Generated by Django 4.2.5 on 2023-09-24 08:53

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import user.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('location', django.contrib.gis.db.models.fields.GeometryField(blank=True, geography=True, null=True, srid=4326, verbose_name='موقعیت')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNumber', models.CharField(db_index=True, max_length=11, unique=True, validators=[user.validators.check_phone], verbose_name='Phone Number')),
                ('type', models.CharField(choices=[('1', 'Admin'), ('2', 'Customer'), ('3', 'Delivery')], default='2', verbose_name='Type of User')),
            ],
            options={
                'verbose_name': 'Table of Users',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('userId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user.user', verbose_name='User Id')),
                ('fullName', models.CharField(blank=True, max_length=200, verbose_name='Full Name')),
                ('birthDate', models.DateField(blank=True, max_length=200, verbose_name='Data of Birth')),
            ],
            options={
                'verbose_name': "Table of Users' Profile",
            },
        ),
    ]
