# Generated by Django 4.2.4 on 2023-09-24 07:32

from django.db import migrations, models
import django.db.models.deletion
import user.validators


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Table of Users'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': "Table of Users' Profile"},
        ),
        migrations.AlterField(
            model_name='user',
            name='phoneNumber',
            field=models.CharField(db_index=True, max_length=11, unique=True, validators=[user.validators.check_phone], verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('1', 'Admin'), ('2', 'Customer'), ('3', 'Delivery')], default='2', verbose_name='Type of User'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='birthDate',
            field=models.DateField(blank=True, max_length=200, verbose_name='Data of Birth'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='fullName',
            field=models.CharField(blank=True, max_length=200, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='userId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user.user', verbose_name='User Id'),
        ),
    ]
