# Generated by Django 4.2.5 on 2023-09-25 09:39

from django.db import migrations, models
import user.validators


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_user_myuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'verbose_name': 'User'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User Profile'},
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='birthDate',
            new_name='birth_date',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='fullName',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='userId',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='phoneNumber',
        ),
        migrations.AddField(
            model_name='myuser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active/ Not Active'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='phone_number',
            field=models.CharField(db_index=True, default='', max_length=11, unique=True, validators=[user.validators.check_phone], verbose_name='Mobile Phone Number'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='slug',
            field=models.SlugField(default='', max_length=200, verbose_name='Slug'),
        ),
    ]
