# Generated by Django 4.2.5 on 2023-09-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_myuser_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertype',
            name='title',
            field=models.CharField(max_length=200, unique=True, verbose_name='Title'),
        ),
    ]
