# Generated by Django 4.2.5 on 2023-09-25 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodcategory',
            name='title',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='title'),
        ),
    ]
