# Generated by Django 4.2.5 on 2023-09-27 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_foodcategory_is_active_foodcategory_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='foodcategory',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='food',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='foodcategory',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
